// База даних емоційних станів при циклотимії
// Кожен стан має: id, label (укр.), emoji, category, moodRange, phaseHint, symptoms

export const EMOTIONAL_CATEGORIES = {
  elevated: {
    label: 'Піднесений / Гіпоманічний',
    color: 'amber',
    bgClass: 'bg-amber-50',
    textClass: 'text-amber-700',
    badgeClass: 'bg-amber-100 text-amber-700',
    phase: 'hypomanic',
  },
  depressive: {
    label: 'Депресивний',
    color: 'blue',
    bgClass: 'bg-blue-50',
    textClass: 'text-blue-700',
    badgeClass: 'bg-blue-100 text-blue-700',
    phase: 'depressive',
  },
  aggressive: {
    label: 'Агресивний / Дратівливий',
    color: 'red',
    bgClass: 'bg-red-50',
    textClass: 'text-red-700',
    badgeClass: 'bg-red-100 text-red-700',
    phase: 'aggressive',
  },
  anxious: {
    label: 'Тривожний',
    color: 'orange',
    bgClass: 'bg-orange-50',
    textClass: 'text-orange-700',
    badgeClass: 'bg-orange-100 text-orange-700',
    phase: 'anxious',
  },
  dysphoric: {
    label: 'Дисфоричний',
    color: 'purple',
    bgClass: 'bg-purple-50',
    textClass: 'text-purple-700',
    badgeClass: 'bg-purple-100 text-purple-700',
    phase: 'dysphoric',
  },
  apathetic: {
    label: 'Апатичний',
    color: 'slate',
    bgClass: 'bg-slate-50',
    textClass: 'text-slate-600',
    badgeClass: 'bg-slate-100 text-slate-600',
    phase: 'apathetic',
  },
  neutral: {
    label: 'Нейтральний / Стабільний',
    color: 'emerald',
    bgClass: 'bg-emerald-50',
    textClass: 'text-emerald-700',
    badgeClass: 'bg-emerald-100 text-emerald-700',
    phase: 'stable',
  },
};

export const EMOTIONAL_STATES = [
  // ─── ПІДНЕСЕНІ / ГІПОМАНІЧНІ ───────────────────────────────
  {
    id: 'euphoric',
    label: 'Ейфорія',
    emoji: '🤩',
    category: 'elevated',
    moodLevel: 5,
    description: 'Надмірна радість, нереалістичний оптимізм',
    symptoms: ['Грандіозність', 'Знижена потреба у сні', 'Прискорена мова', 'Ризикована поведінка'],
  },
  {
    id: 'hypomanic_energy',
    label: 'Гіпоманічна енергія',
    emoji: '⚡',
    category: 'elevated',
    moodLevel: 4,
    description: 'Сильний підйом енергії та активності',
    symptoms: ['Підвищена енергія', 'Знижена потреба у сні', 'Імпульсивність', 'Висока продуктивність'],
  },
  {
    id: 'elevated_mood',
    label: 'Піднесений настрій',
    emoji: '😄',
    category: 'elevated',
    moodLevel: 3,
    description: 'Виразне покращення настрою вище звичайного',
    symptoms: ['Підвищена комунікабельність', 'Зниження критичності', 'Творчий підйом'],
  },
  {
    id: 'optimistic',
    label: 'Оптимізм',
    emoji: '🌟',
    category: 'elevated',
    moodLevel: 2,
    description: 'Позитивне сприйняття майбутнього',
    symptoms: ['Впевненість у собі', 'Ініціативність'],
  },
  {
    id: 'slightly_elevated',
    label: 'Легке піднесення',
    emoji: '🙂',
    category: 'elevated',
    moodLevel: 1,
    description: 'Трохи краще за звичайний стан',
    symptoms: [],
  },

  // ─── НЕЙТРАЛЬНІ / СТАБІЛЬНІ ────────────────────────────────
  {
    id: 'calm',
    label: 'Спокій',
    emoji: '😌',
    category: 'neutral',
    moodLevel: 0,
    description: 'Врівноважений, стабільний стан',
    symptoms: [],
  },
  {
    id: 'content',
    label: 'Задоволеність',
    emoji: '😊',
    category: 'neutral',
    moodLevel: 0,
    description: 'Тихе відчуття добробуту',
    symptoms: [],
  },
  {
    id: 'neutral',
    label: 'Нейтральний',
    emoji: '😐',
    category: 'neutral',
    moodLevel: 0,
    description: 'Ні гарно, ні погано',
    symptoms: [],
  },

  // ─── ДЕПРЕСИВНІ ────────────────────────────────────────────
  {
    id: 'slightly_sad',
    label: 'Легка сум',
    emoji: '😕',
    category: 'depressive',
    moodLevel: -1,
    description: 'Трохи знижений настрій',
    symptoms: ['Легка втома'],
  },
  {
    id: 'sad',
    label: 'Смуток',
    emoji: '🙁',
    category: 'depressive',
    moodLevel: -2,
    description: 'Помітний смуток, зниження задоволення',
    symptoms: ['Зниження апетиту', 'Плаксивість', 'Зниження мотивації'],
  },
  {
    id: 'depressed',
    label: 'Пригніченість',
    emoji: '😔',
    category: 'depressive',
    moodLevel: -3,
    description: 'Виразна депресивна симптоматика',
    symptoms: ['Втома', 'Складність зосередитися', 'Безнадійність', 'Самоізоляція'],
  },
  {
    id: 'deep_depression',
    label: 'Депресія',
    emoji: '😢',
    category: 'depressive',
    moodLevel: -4,
    description: 'Глибока депресія, щоденне функціонування порушено',
    symptoms: ['Апатія', 'Надмірний сон', 'Безнадійність', 'Плаксивість', 'Самоізоляція'],
  },
  {
    id: 'severe_depression',
    label: 'Тяжка депресія',
    emoji: '😞',
    category: 'depressive',
    moodLevel: -5,
    description: 'Найважчий депресивний стан',
    symptoms: ['Апатія', 'Надмірний сон', 'Безнадійність', 'Нездатність діяти'],
  },
  {
    id: 'hopelessness',
    label: 'Безнадійність',
    emoji: '🌑',
    category: 'depressive',
    moodLevel: -4,
    description: 'Відчуття що ситуація не зміниться',
    symptoms: ['Безнадійність', 'Пасивність', 'Суїцидальні думки'],
  },
  {
    id: 'emptiness',
    label: 'Порожнеча',
    emoji: '🕳️',
    category: 'depressive',
    moodLevel: -3,
    description: 'Внутрішня порожнеча, відсутність емоцій',
    symptoms: ['Емоційне оніміння', 'Відчуженість'],
  },

  // ─── АГРЕСИВНІ / ДРАТІВЛИВІ ────────────────────────────────
  {
    id: 'irritable',
    label: 'Дратівливість',
    emoji: '😤',
    category: 'aggressive',
    moodLevel: 1,
    description: 'Легке роздратування, нестерпність',
    symptoms: ['Дратівливість', 'Нетерпіння'],
  },
  {
    id: 'angry',
    label: 'Злість',
    emoji: '😠',
    category: 'aggressive',
    moodLevel: 2,
    description: 'Виразна злість, важко стримуватися',
    symptoms: ['Дратівливість', 'Конфліктність', 'Підвищений голос'],
  },
  {
    id: 'rage',
    label: 'Лють',
    emoji: '🤬',
    category: 'aggressive',
    moodLevel: 3,
    description: 'Сильна неконтрольована лють',
    symptoms: ['Агресія', 'Вибухи гніву', 'Фізична напруга', 'Руйнівна поведінка'],
  },
  {
    id: 'hostile',
    label: 'Ворожість',
    emoji: '😡',
    category: 'aggressive',
    moodLevel: 2,
    description: 'Загальна ворожість до оточуючих',
    symptoms: ['Недовіра', 'Конфліктність', 'Провокаційна поведінка'],
  },
  {
    id: 'agitated',
    label: 'Збудженість',
    emoji: '🔥',
    category: 'aggressive',
    moodLevel: 3,
    description: 'Внутрішнє збудження, неможливість розслабитися',
    symptoms: ['Рухове збудження', 'Метушливість', 'Дратівливість', 'Безсоння'],
  },

  // ─── ТРИВОЖНІ ──────────────────────────────────────────────
  {
    id: 'worried',
    label: 'Занепокоєння',
    emoji: '😟',
    category: 'anxious',
    moodLevel: -1,
    description: 'Легка тривога, постійні думки про проблеми',
    symptoms: ['Тривожні думки', 'Напруженість'],
  },
  {
    id: 'anxious',
    label: 'Тривога',
    emoji: '😰',
    category: 'anxious',
    moodLevel: -2,
    description: 'Виразна тривога, важко зосередитися',
    symptoms: ['Тривога', 'Серцебиття', 'Напруженість м\'язів', 'Складність зосередитися'],
  },
  {
    id: 'panic',
    label: 'Паніка',
    emoji: '😱',
    category: 'anxious',
    moodLevel: -3,
    description: 'Панічні атаки або стан близький до них',
    symptoms: ['Панічні атаки', 'Серцебиття', 'Задуха', 'Страх смерті', 'Запаморочення'],
  },
  {
    id: 'fear',
    label: 'Страх',
    emoji: '😨',
    category: 'anxious',
    moodLevel: -2,
    description: 'Сильний страх без конкретної причини',
    symptoms: ['Страх', 'Уникаюча поведінка', 'Тремтіння'],
  },
  {
    id: 'hypervigilance',
    label: 'Гіпербдительність',
    emoji: '👁️',
    category: 'anxious',
    moodLevel: -1,
    description: 'Постійна настороженість, очікування небезпеки',
    symptoms: ['Надмірна пильність', 'Порушення сну', 'Перебільшена реакція на подразники'],
  },

  // ─── ДИСФОРИЧНІ ────────────────────────────────────────────
  {
    id: 'dysphoric',
    label: 'Дисфорія',
    emoji: '😖',
    category: 'dysphoric',
    moodLevel: -2,
    description: 'Змішаний стан: збудження + пригнічення одночасно',
    symptoms: ['Внутрішня напруга', 'Дратівливість', 'Пригніченість', 'Нездатність розслабитися'],
  },
  {
    id: 'mixed_state',
    label: 'Змішаний стан',
    emoji: '🌪️',
    category: 'dysphoric',
    moodLevel: -1,
    description: 'Одночасно підйом і депресія, хаос',
    symptoms: ['Прискорені думки', 'Пригніченість', 'Агітація', 'Безсоння'],
  },
  {
    id: 'restless',
    label: 'Неспокій',
    emoji: '🫨',
    category: 'dysphoric',
    moodLevel: -1,
    description: 'Внутрішнє неспокійне відчуття, не можна знайти місця',
    symptoms: ['Неспокій', 'Метушливість', 'Нездатність сидіти на місці'],
  },
  {
    id: 'dissociative',
    label: 'Деперсоналізація',
    emoji: '🌫️',
    category: 'dysphoric',
    moodLevel: -2,
    description: 'Відчуженість від себе або реальності',
    symptoms: ['Відчуженість', 'Нереальність відчуттів', 'Емоційне оніміння'],
  },

  // ─── АПАТИЧНІ ──────────────────────────────────────────────
  {
    id: 'apathy',
    label: 'Апатія',
    emoji: '😶',
    category: 'apathetic',
    moodLevel: -3,
    description: 'Повна відсутність мотивації та інтересу',
    symptoms: ['Апатія', 'Втрата інтересів', 'Пасивність', 'Надмірний сон'],
  },
  {
    id: 'emotional_numbness',
    label: 'Емоційне оніміння',
    emoji: '🧊',
    category: 'apathetic',
    moodLevel: -2,
    description: 'Нездатність відчувати емоції',
    symptoms: ['Емоційне оніміння', 'Відчуженість', 'Механічна поведінка'],
  },
  {
    id: 'exhaustion',
    label: 'Виснаження',
    emoji: '🪫',
    category: 'apathetic',
    moodLevel: -3,
    description: 'Повне фізичне та емоційне виснаження',
    symptoms: ['Хронічна втома', 'Нездатність діяти', 'Надмірний сон', 'Ломота в тілі'],
  },
  {
    id: 'anhedonia',
    label: 'Ангедонія',
    emoji: '🎭',
    category: 'apathetic',
    moodLevel: -3,
    description: 'Нездатність отримувати задоволення від приємних речей',
    symptoms: ['Втрата інтересів', 'Відсутність радості', 'Соціальна ізоляція'],
  },
];

// Групування за категоріями для дропдауну
export const STATES_BY_CATEGORY = Object.keys(EMOTIONAL_CATEGORIES).reduce((acc, cat) => {
  acc[cat] = EMOTIONAL_STATES.filter(s => s.category === cat);
  return acc;
}, {});

export const getStateById = (id) => EMOTIONAL_STATES.find(s => s.id === id);
export const getStatesByCategory = (cat) => EMOTIONAL_STATES.filter(s => s.category === cat);
